/**
 * Launcher scripts for the `igv-vscode` CLI (spec §6.4). The launcher runs
 * dist/cli.js with the extension host's own runtime (Electron with
 * ELECTRON_RUN_AS_NODE=1 on desktop, plain Node on code-server), so no system
 * Node is needed. Regenerated on every activation because paths change with
 * updates. No `vscode` dependency.
 */
import * as fs from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';

export interface LauncherPaths {
  binDir: string;
  posix: string;
  windows: string;
}

export function posixLauncher(execPath: string, cliPath: string): string {
  const q = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;
  return `#!/bin/sh
# igv-vscode CLI launcher (generated by the IGV Viewer extension; do not edit)
ELECTRON_RUN_AS_NODE=1 exec ${q(execPath)} ${q(cliPath)} "$@"
`;
}

export function windowsLauncher(execPath: string, cliPath: string): string {
  return `@echo off\r
rem igv-vscode CLI launcher (generated by the IGV Viewer extension; do not edit)\r
set ELECTRON_RUN_AS_NODE=1\r
"${execPath}" "${cliPath}" %*\r
`;
}

export async function writeLaunchers(binDir: string, execPath: string, cliPath: string): Promise<LauncherPaths> {
  await fs.mkdir(binDir, { recursive: true });
  const posix = path.join(binDir, 'igv-vscode');
  const windows = path.join(binDir, 'igv-vscode.cmd');
  await fs.writeFile(posix, posixLauncher(execPath, cliPath), { mode: 0o755 });
  await fs.chmod(posix, 0o755).catch(() => undefined);
  await fs.writeFile(windows, windowsLauncher(execPath, cliPath));
  return { binDir, posix, windows };
}

export interface InstallResult {
  installed: boolean;
  target?: string;
  message: string;
}

/**
 * "IGV: Install CLI on PATH": symlink the POSIX launcher into ~/.local/bin
 * (created if needed). On Windows, return instructions instead.
 */
export async function installOnPath(launchers: LauncherPaths, homeDir = os.homedir(), platform = process.platform): Promise<InstallResult> {
  if (platform === 'win32') {
    return {
      installed: false,
      message: `Add this folder to your PATH (System Properties → Environment Variables): ${launchers.binDir}\nThen open a new terminal and run: igv-vscode --help`,
    };
  }
  const dir = path.join(homeDir, '.local', 'bin');
  await fs.mkdir(dir, { recursive: true });
  const target = path.join(dir, 'igv-vscode');
  try {
    const st = await fs.lstat(target);
    if (st.isSymbolicLink() || st.isFile()) await fs.rm(target, { force: true });
  } catch {
    // not there
  }
  await fs.symlink(launchers.posix, target);
  const onPath = (process.env.PATH ?? '').split(path.delimiter).includes(dir);
  return {
    installed: true,
    target,
    message: onPath
      ? `Installed ${target}. Run "igv-vscode --help" in any terminal.`
      : `Installed ${target}. ${dir} is not on your PATH yet; add it to your shell profile, e.g.\n  export PATH="$HOME/.local/bin:$PATH"`,
  };
}
